### PR TITLE
Create Bug & FR template for SDKs

### PR DESCRIPTION
**Pull request by Dawntraoz**
Create a new issue template for SDKs to add reproduction and labels from the beginning.

### CODE REVIEW

**Comment by ademarCardoso** [comment]
Will this change be for all repositories?

cc: @Dawntraoz @alexjoverm

**Comment by Dawntraoz** [comment]
> Will this change be for all repositories?
> 
> cc: @Dawntraoz @alexjoverm

We wanted to have them in a subset of repos (the SDKs), but as we couldn't find the way (cc @christianzoppi), I added a title specifying it is an SDK template. Is that okay? What will be your solution to create a shared template?

**Comment by arisa-fukuzaki** [comment]
@Dawntraoz Thanks for working on this task!

Should we include a Code of Conduct unless it's irrelevant or if you already had it somewhere relevant? What do you think?

**Comment by ademarCardoso** [comment]
cc: @Dawntraoz

**Comment by ademarCardoso** [comment]
I asked because I thought it would impact all the repos, but if it's for the sdks that's fine with me, in the future if necessary we can expand to the other repos 😄 .

About the code of conduct that @schabibi1  commented on, [here's a link](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client), it might be useful. (If implemented here)

cc: @Dawntraoz

**Comment by Dawntraoz** [comment]
> @Dawntraoz Thanks for working on this task!
> 
> Should we include a Code of Conduct unless it's irrelevant or if you already had it somewhere relevant? What do you think?

Do you mean a verification checkbox that they read it with a link? Of course, I can add that!

**Comment by Dawntraoz** [comment]
> I asked because I thought it would impact all the repos, but if it's for the sdks that's fine with me, in the future if necessary we can expand to the other repos 😄 .

It will impact all the repos, because, as I mentioned, we didn't find a way to make it work for a subset of repos 😅

If someone goes to the X repo (not SDK) and click "SDK Bug report" they will create an SDK bug report style in that X repo. But it's that a problem? Maybe I can add another verification checkbox asking if they understand that they're reporting the issues for an SDK and not for a generic SB tool 🤔

**Comment by sebgie** [comment]
As @ademarCardoso already pointed out this will make this new template available on all 200+ repositories. I think it would be sensible to replace the bug template only in the SDK repositories. I know that we then have to update multiple repos but adding it to all sounds wrong as well.

> make it work for a subset of repos
we need to create the issue template in all SDK repos:  `storyblok/<sdk>/ISSUE_TEMPLATE/issue.bug.yml` where we want to have it.

**Comment by Dawntraoz** [comment]
> As @ademarCardoso already pointed out this will make this new template available on all 200+ repositories. I think it would be sensible to replace the bug template only in the SDK repositories. I know that we then have to update multiple repos but adding it to all sounds wrong as well.
> 
> > make it work for a subset of repos
> > we need to create the issue template in all SDK repos:  `storyblok/<sdk>/ISSUE_TEMPLATE/issue.bug.yml` where we want to have it.

Fair enough, I will use then this PR to get feedback from the content of the templates and close it after. Then I will create the equivalent in all the SDKs ✔

**Comment by christianzoppi** [comment]
@Dawntraoz I've done a bit of research on how to deploy these files to a subset of repos and I've just found a GitHub action that could help us :-) It's this [one](https://github.com/BetaHuhn/repo-file-sync-action#%EF%B8%8F-sync-configuration). I'm sending you a quick demo. We don't have so many SDKs to be that worried about the manual work but an automatic flow could be nice anyway in my opinion.

**Comment by Dawntraoz** [comment]
Created the new templates under Storyblok JS SDK using the Sync workflow recommended by @christianzoppi -> https://github.com/storyblok/storyblok-js/pull/286

**Pull request closed without merging**
